Repository tue-bmd/zea, pull requests merged in 2025-06, with the labels that each got.

#13 Add action-perception diagram
  docs/_static/zea_perception_action-Dark.svg
  docs/_static/zea_perception_action-Light.svg
  docs/source/about.rst
Labels: documentation

#7 Dockerfile update
  .github/workflows/ci-pipeline.yaml
  Dockerfile
  Dockerfile.base
  build_all_images.sh
  motd.sh
Labels: dev

#9 Scan docs
  docs/source/about.rst
  docs/source/notebooks/models/custom_models_example.ipynb
  zea/scan.py
Labels: documentation

#17 `zea.ops.Operation.__call__()` Improved error message
  docs/source/notebooks/models/segmentation_example.ipynb
  tests/test_ops_infra.py
  zea/ops.py
Labels: enhancement
