Repository tue-bmd/zea, pull requests merged in 2025-07, with the labels that each got.

#23 Clean-up and improve selecting transmits
  tests/test_scan.py
  zea/internal/parameters.py
  zea/scan.py
Labels: bug

#29 Adds `zea.Folder.copy` method
  tests/conftest.py
  tests/data/test_dataset.py
  zea/data/__main__.py
  zea/data/data_format.py
  zea/data/datasets.py
  zea/data/file.py
Labels: enhancement

#33 Refactor CI/CD Pipeline
  .github/workflows/build-image.yaml
  .github/workflows/ci-pipeline.yaml
  .github/workflows/docker.yaml
  .github/workflows/linter.yaml
  .github/workflows/publish.yaml
  .github/workflows/set-tag.yaml
  .github/workflows/tests.yaml
  README.md
  docs/CONTRIBUTING.md
Labels: dev

#60 Syntax notebook fix
  poetry.lock
  pyproject.toml
  zea/models/base.py
Labels: documentation

#67 Greedy entropy bug fix
  tests/test_agent.py
  zea/agent/selection.py
Labels: bug, agent

#68 Sync configs to HF
  .github/workflows/sync-hf-configs.yaml
  configs/README.md
  docs/source/notebooks/data/zea_data_example.ipynb
  docs/source/notebooks/data/zea_local_data.ipynb
  tests/test_configs.py
  tests/test_notebooks.py
  zea/config.py
Labels: dev

#63 Prevent error when probe is unknown
  tests/test_probes.py
  zea/data/file.py
  zea/internal/registry.py
  zea/probes.py
Labels: bug
